export const ROLES = {
    TUTOR: 'TUTOR',
};

export const STUDENT_STATUS = {
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    GRADUATED: 'GRADUATED',
    DROPPED: 'DROPPED',
};

export const SESSION_STATUS = {
    SCHEDULED: 'SCHEDULED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    MISSED: 'MISSED',
    RESCHEDULED: 'RESCHEDULED',
};

export const ATTENDANCE_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    CANCELLED: 'CANCELLED',
    LATE: 'LATE',
};

export const HOMEWORK_STATUS = {
    ASSIGNED: 'ASSIGNED',
    SUBMITTED: 'SUBMITTED',
    PENDING: 'PENDING',
    OVERDUE: 'OVERDUE',
    EXCUSED: 'EXCUSED',
};

export const EMAIL_STATUS = {
    PENDING: 'PENDING',
    SENT: 'SENT',
    FAILED: 'FAILED',
    BOUNCED: 'BOUNCED',
};

export const EMAIL_TYPE = {
    SESSION_SUMMARY: 'SESSION_SUMMARY',
    REMINDER: 'REMINDER',
    HOMEWORK: 'HOMEWORK',
    BIRTHDAY: 'BIRTHDAY',
    FEE: 'FEE',
    CUSTOM: 'CUSTOM',
};

export const NOTIFICATION_TYPE = {
    SESSION_REMINDER: 'SESSION_REMINDER',
    SESSION_MISSED: 'SESSION_MISSED',
    HOMEWORK_PENDING: 'HOMEWORK_PENDING',
    HOMEWORK_OVERDUE: 'HOMEWORK_OVERDUE',
    BIRTHDAY: 'BIRTHDAY',
    FEE_DUE: 'FEE_DUE',
    SESSION_CONFLICT: 'SESSION_CONFLICT',
    GOAL_DEADLINE: 'GOAL_DEADLINE',
};

export const NOTIFICATION_PRIORITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT',
};

export const ACTIVITY_TYPE = {
    STUDENT_CREATED: 'STUDENT_CREATED',
    STUDENT_UPDATED: 'STUDENT_UPDATED',
    STUDENT_DELETED: 'STUDENT_DELETED',
    STUDENT_RESTORED: 'STUDENT_RESTORED',
    SESSION_CREATED: 'SESSION_CREATED',
    SESSION_UPDATED: 'SESSION_UPDATED',
    SESSION_CANCELLED: 'SESSION_CANCELLED',
    SESSION_COMPLETED: 'SESSION_COMPLETED',
    SESSION_RESCHEDULED: 'SESSION_RESCHEDULED',
    SUMMARY_CREATED: 'SUMMARY_CREATED',
    SUMMARY_EMAILED: 'SUMMARY_EMAILED',
    HOMEWORK_CREATED: 'HOMEWORK_CREATED',
    HOMEWORK_UPDATED: 'HOMEWORK_UPDATED',
    HOMEWORK_SUBMITTED: 'HOMEWORK_SUBMITTED',
    ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
    GOAL_CREATED: 'GOAL_CREATED',
    GOAL_COMPLETED: 'GOAL_COMPLETED',
};

export const PERFORMANCE_LEVEL = {
    EXCELLENT: 'EXCELLENT',
    GOOD: 'GOOD',
    AVERAGE: 'AVERAGE',
    NEEDS_IMPROVEMENT: 'NEEDS_IMPROVEMENT',
};

export const ENTITY_TYPE = {
    STUDENT: 'STUDENT',
    SESSION: 'SESSION',
    SUMMARY: 'SUMMARY',
    HOMEWORK: 'HOMEWORK',
    ATTENDANCE: 'ATTENDANCE',
    GOAL: 'GOAL',
    FORMULA: 'FORMULA',
    DOUBT: 'DOUBT',
};
